### ISSUE TITLE
XML documentation file

### ISSUE THREAD

**Issue by lkurzyniec** [maldworth/aldsoft.acord#2]
Could you enable **XML documentation file** and include it into the nuget package. It would be great to have IntelliSense in VS.

I have tried to build your project via gulp, but it failed, so I can't make PR.

**Comment by maldworth** [comment]
I've updated the develop branch with a fix that makes gulp nuget happy. Please make a PR whenever you get a chance.

**Comment by maldworth** [comment]
This should now be done with the latest Release 0.3.0
