### ISSUE TITLE
TXLife2 xsd question

### ISSUE THREAD

**Issue by stephenpatten** [maldworth/aldsoft.acord#3]
Hello,

First off, thank you for an awesome library. 

I have access to the Acord xsds, and have a copy of xsd2code++, but there are 4 of them

TXLife2.40.00.xsd
TXLife2.40.00clean.xsd
TXLife2.40.00enum.xsd
TXLife2.40.00fulldoc.xsd

Which one do you use to gen the TX? I'm also wanting to gen without IPropertyNotify and may split the classes.

Any help would be appreciated. I 'could' PR it too if you wanted.

Thank you,
Stephen

**Comment by maldworth** [comment]
I'm doing some updates in a branch (.net core support), plus it will have a powershell you can use which has the params to pass into xsd2code++ for generation.
Also, I agree, the IPropertyNotify stuff is unnecessary and will be removed in the generation.

If you wait a few more days I should have the branch for you to use. And then a PR back in with the 2.40 generated Cs file would be great!

**Comment by stephenpatten** [comment]
Sounds like a plan.

**Comment by maldworth** [comment]
I'll need some more time. Spent some time tinkering around and am having trouble finding the original settings that were used to generate.

**Comment by stephenpatten** [comment]
They're in the header of the TXLife file, right?

**Comment by maldworth** [comment]
Yeah I have the params the same. The problem is it seems to be generating differently. The only variable is I think updates to VS and the .net framework have updated the xsd.exe running. Anyways it's generating,  but now the unit tests are failing. So I'm going to chip away at that.

**Comment by maldworth** [comment]
Good news, I have a branch you can use. it's called feat/cakebuild
Has a /generate folder. All you need to do it put the schema in a folder under the generate folder (./generate/schemas), and run the powershell.. should handle everything from there, and copy it to the csproj folder as well.

I still have some cakebuild and appveyor items to cleanup in there. I should get to that this weekend.

**Comment by stephenpatten** [comment]
I did a quick deep dive last night with 2.38 but then was really confused
when I found a 2.40 folder, I chalked it up to being tired :) but in fact
you had added an empty 22.40 project folder. I have the 2.38 and 2.40 xsds
atm
 and will try to back fill between 2.35 and 2.40 once our rep gives me the
missing ones. For the time being I'll try 2.38 to stay out of your way.

-Stephen

**Comment by maldworth** [comment]
I added the 2.40 folder for you, just to get it ready :). But please feel free to add folders/csproj for each version you have.

**Comment by stephenpatten** [comment]
I just ran 38 and 40 in one batch, nice script btw.

**Comment by stephenpatten** [comment]
Ah crap!

I've never participated on GitHub, so I may have done my branch wrong from
the beginning, sorry. I cloned feat/cake and made the changes in my local
branch, can you add stephenpatten as a contibutor? v 2.38 / v 2.40 are
done, less the tests.

**Comment by maldworth** [comment]
I see you got it. Typically how you do it is you create a fork, then make your changes. Then submit a PR from your repo into here. If you ever want to contribute more, and you want my changes (for example from master branch). You would have to set up an "upstream remote" to my repo. `git remote add upstream...`. Then any updates I put into master here, you could pull them into your fork with `git pull upstream master` for example.

Thanks for PR #4 Added the tests and everything is passing. So the last bit is getting the packages into nuget.

**Comment by maldworth** [comment]
Okay, 0.3.0 is released. thanks for all your help.

**Comment by stephenpatten** [comment]
The pleasure is mine.

I love reading good code and this was an opportunity to explore a few new
concepts, like the command-line args being passed to xsd2code in
power-shell, cake builds.

Next, I'm going to explore serializing objects graphs when the TXLife is
single file, or broken down into constituent classes. Maybe we got rid of
the pause when loading due to INotifyProperyChange.

I also see you work on MassTransit. I have an opportunity to rewrite a home
grown "notification engine" that polls a database queue... with something
more event driven. MT also supports both RabbitMQ and SQS transports, which
is a plus since we have a roadmap to the cloud in the next 4 years.

**Comment by maldworth** [comment]
Object graphs, that sounds fun. Thank you, and MassTransit is a really great abstraction to help get introduced into the world of Service Buses. Whenever I hear people are interfacing directly with RabbitMQ, or AzureSB, or SQS, I always try to steer them towards MassTransit.

When you start tackling that re-write, if you ever have any questions about MassTransit head over to the [Gitter Channel](https://gitter.im/MassTransit/MassTransit). There's always a helpful community member there (sometimes myself).

Cheers!
